import { defineConfig } from '@hey-api/openapi-ts';

export default defineConfig({
  input: {
    path: 'src/lib/api/spec/openapi.json'
  },
  output: {
    header: [
      '/* eslint-disable */',
      '// This file is auto-generated by @hey-api/openapi-ts',
    ],
    path: 'src/lib/api/client'
  },
  plugins: [
    {
      name: '@hey-api/client-fetch',
      runtimeConfigPath: '@/lib/api/create-client-config',
    }
  ]
});
