// This file is auto-generated by @hey-api/openapi-ts
import 'server-only';

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateSubscriptionData, CreateSubscriptionResponses, GetArticleData, GetArticleErrors, GetArticleResponses, GetBreakingNewsData, GetBreakingNewsResponses, GetPublicationConfigData, GetPublicationConfigResponses, GetSubscriptionData, GetSubscriptionErrors, GetSubscriptionResponses, GetTrendingArticlesData, GetTrendingArticlesResponses, HealthCheckData, HealthCheckResponses, ListArticlesData, ListArticlesErrors, ListArticlesResponses, ListCategoriesData, ListCategoriesResponses, SubscribeData, SubscribeErrors, SubscribeResponses, UnsubscribeData, UnsubscribeErrors, UnsubscribeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List articles
 *
 * Returns a paginated list of articles. Supports filtering by category, search term, and featured status.
 */
export const listArticles = <ThrowOnError extends boolean = false>(options?: Options<ListArticlesData, ThrowOnError>) => (options?.client ?? client).get<ListArticlesResponses, ListArticlesErrors, ThrowOnError>({
    security: [{ name: 'x-vercel-protection-bypass', type: 'apiKey' }],
    url: '/articles',
    ...options
});

/**
 * Get article details
 *
 * Returns a single article by its ID or slug.
 */
export const getArticle = <ThrowOnError extends boolean = false>(options: Options<GetArticleData, ThrowOnError>) => (options.client ?? client).get<GetArticleResponses, GetArticleErrors, ThrowOnError>({
    security: [{ name: 'x-vercel-protection-bypass', type: 'apiKey' }],
    url: '/articles/{id}',
    ...options
});

/**
 * Get trending articles
 *
 * Returns 4 randomly selected trending articles. Results change on every request. Use the exclude parameter to filter out articles already displayed.
 */
export const getTrendingArticles = <ThrowOnError extends boolean = false>(options?: Options<GetTrendingArticlesData, ThrowOnError>) => (options?.client ?? client).get<GetTrendingArticlesResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-vercel-protection-bypass', type: 'apiKey' }],
    url: '/articles/trending',
    ...options
});

/**
 * List all categories
 *
 * Returns all article categories with their article counts.
 */
export const listCategories = <ThrowOnError extends boolean = false>(options?: Options<ListCategoriesData, ThrowOnError>) => (options?.client ?? client).get<ListCategoriesResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-vercel-protection-bypass', type: 'apiKey' }],
    url: '/categories',
    ...options
});

/**
 * Get breaking news
 *
 * Returns a randomly selected breaking news item. May return a different item on each request.
 */
export const getBreakingNews = <ThrowOnError extends boolean = false>(options?: Options<GetBreakingNewsData, ThrowOnError>) => (options?.client ?? client).get<GetBreakingNewsResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-vercel-protection-bypass', type: 'apiKey' }],
    url: '/breaking-news',
    ...options
});

/**
 * Deactivate subscription
 *
 * Deactivates the subscription (sets status to inactive). Requires the `x-subscription-token` header.
 */
export const unsubscribe = <ThrowOnError extends boolean = false>(options: Options<UnsubscribeData, ThrowOnError>) => (options.client ?? client).delete<UnsubscribeResponses, UnsubscribeErrors, ThrowOnError>({
    security: [{ name: 'x-vercel-protection-bypass', type: 'apiKey' }],
    url: '/subscription',
    ...options
});

/**
 * Get subscription status
 *
 * Retrieves the current subscription status. Requires the `x-subscription-token` header.
 */
export const getSubscription = <ThrowOnError extends boolean = false>(options: Options<GetSubscriptionData, ThrowOnError>) => (options.client ?? client).get<GetSubscriptionResponses, GetSubscriptionErrors, ThrowOnError>({
    security: [{ name: 'x-vercel-protection-bypass', type: 'apiKey' }],
    url: '/subscription',
    ...options
});

/**
 * Activate subscription
 *
 * Activates the subscription (sets status to active). Requires the `x-subscription-token` header.
 */
export const subscribe = <ThrowOnError extends boolean = false>(options: Options<SubscribeData, ThrowOnError>) => (options.client ?? client).post<SubscribeResponses, SubscribeErrors, ThrowOnError>({
    security: [{ name: 'x-vercel-protection-bypass', type: 'apiKey' }],
    url: '/subscription',
    ...options
});

/**
 * Create a new subscription
 *
 * Creates a new inactive subscription. The response includes the subscription token in the `x-subscription-token` response header. Store this token and include it in all subsequent subscription requests.
 */
export const createSubscription = <ThrowOnError extends boolean = false>(options?: Options<CreateSubscriptionData, ThrowOnError>) => (options?.client ?? client).post<CreateSubscriptionResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-vercel-protection-bypass', type: 'apiKey' }],
    url: '/subscription/create',
    ...options
});

/**
 * Get publication configuration
 *
 * Returns publication configuration including enabled features, social links, and SEO defaults.
 */
export const getPublicationConfig = <ThrowOnError extends boolean = false>(options?: Options<GetPublicationConfigData, ThrowOnError>) => (options?.client ?? client).get<GetPublicationConfigResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-vercel-protection-bypass', type: 'apiKey' }],
    url: '/publication/config',
    ...options
});

/**
 * Health check
 *
 * Returns the health status of the API and its dependent services (Redis).
 */
export const healthCheck = <ThrowOnError extends boolean = false>(options?: Options<HealthCheckData, ThrowOnError>) => (options?.client ?? client).get<HealthCheckResponses, unknown, ThrowOnError>({
    security: [{ name: 'x-vercel-protection-bypass', type: 'apiKey' }],
    url: '/health',
    ...options
});
