/* eslint-disable */
// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://vercel-daily-news-api.vercel.app/api' | (string & {});
};

export type Author = {
    name?: string;
    avatar?: string;
};

export type ContentBlock = {
    type: 'paragraph';
    text: string;
} | {
    type: 'heading';
    level: 2 | 3;
    text: string;
} | {
    type: 'blockquote';
    text: string;
} | {
    type: 'unordered-list';
    items: Array<string>;
} | {
    type: 'ordered-list';
    items: Array<string>;
} | {
    type: 'image';
    src: string;
    alt: string;
    caption?: string;
};

export type Article = {
    id?: string;
    title?: string;
    slug?: string;
    excerpt?: string;
    /**
     * Structured content blocks. See the 'Rendering Article Content' section for details.
     */
    content?: Array<ContentBlock>;
    category?: string;
    author?: Author;
    image?: string;
    publishedAt?: string;
    /**
     * Whether this article is featured on the homepage
     */
    featured?: boolean;
    tags?: Array<string>;
};

export type BreakingNews = {
    id?: string;
    headline?: string;
    summary?: string;
    articleId?: string;
    category?: string;
    publishedAt?: string;
    urgent?: boolean;
};

export type Subscription = {
    token?: string;
    status?: 'active' | 'inactive';
    subscribedAt?: string;
    createdAt?: string;
    updatedAt?: string;
};

export type Category = {
    slug?: string;
    name?: string;
    articleCount?: number;
};

export type PaginationMeta = {
    page?: number;
    limit?: number;
    total?: number;
    totalPages?: number;
    hasNextPage?: boolean;
    hasPreviousPage?: boolean;
};

export type ArticleListResponse = {
    success?: boolean;
    data?: Array<Article>;
    meta?: {
        pagination?: PaginationMeta;
    };
};

export type ArticleResponse = {
    success?: boolean;
    data?: Article;
};

export type CategoryListResponse = {
    success?: boolean;
    data?: Array<Category>;
};

export type BreakingNewsResponse = {
    success?: boolean;
    data?: BreakingNews;
};

export type SubscriptionResponse = {
    success?: boolean;
    data?: Subscription;
};

export type ErrorResponse = {
    success?: boolean;
    error?: {
        code?: string;
        message?: string;
        /**
         * Additional error details (validation errors, etc.)
         */
        details?: unknown;
    };
};

export type ListArticlesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page number (starts at 1)
         */
        page?: number;
        /**
         * Items per page (max 100)
         */
        limit?: number;
        /**
         * Filter by category slug
         */
        category?: 'changelog' | 'engineering' | 'customers' | 'company-news' | 'community';
        /**
         * Search articles by title, excerpt, or tags
         */
        search?: string;
        /**
         * Filter by featured status
         */
        featured?: 'true' | 'false';
    };
    url: '/articles';
};

export type ListArticlesErrors = {
    /**
     * Validation error
     */
    422: ErrorResponse;
};

export type ListArticlesError = ListArticlesErrors[keyof ListArticlesErrors];

export type ListArticlesResponses = {
    /**
     * Paginated article list
     */
    200: ArticleListResponse;
};

export type ListArticlesResponse = ListArticlesResponses[keyof ListArticlesResponses];

export type GetArticleData = {
    body?: never;
    path: {
        /**
         * Article ID (e.g. 4eUawbAqhHBg0OzTSNeLwv) or slug (e.g. building-secure-ai-agents)
         */
        id: string;
    };
    query?: never;
    url: '/articles/{id}';
};

export type GetArticleErrors = {
    /**
     * Article not found
     */
    404: ErrorResponse;
};

export type GetArticleError = GetArticleErrors[keyof GetArticleErrors];

export type GetArticleResponses = {
    /**
     * Article details
     */
    200: ArticleResponse;
};

export type GetArticleResponse = GetArticleResponses[keyof GetArticleResponses];

export type GetTrendingArticlesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Comma-separated list of article IDs to exclude (e.g. 4eUawbAqhHBg0OzTSNeLwv,6tdBZO7G0ySd5jrFwyw4Nq)
         */
        exclude?: string;
    };
    url: '/articles/trending';
};

export type GetTrendingArticlesResponses = {
    /**
     * Trending articles
     */
    200: {
        success?: boolean;
        data?: Array<Article>;
    };
};

export type GetTrendingArticlesResponse = GetTrendingArticlesResponses[keyof GetTrendingArticlesResponses];

export type ListCategoriesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/categories';
};

export type ListCategoriesResponses = {
    /**
     * List of categories
     */
    200: CategoryListResponse;
};

export type ListCategoriesResponse = ListCategoriesResponses[keyof ListCategoriesResponses];

export type GetBreakingNewsData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/breaking-news';
};

export type GetBreakingNewsResponses = {
    /**
     * Breaking news item
     */
    200: BreakingNewsResponse;
};

export type GetBreakingNewsResponse = GetBreakingNewsResponses[keyof GetBreakingNewsResponses];

export type UnsubscribeData = {
    body?: never;
    headers: {
        /**
         * The subscription token received when creating a subscription
         */
        'x-subscription-token': string;
    };
    path?: never;
    query?: never;
    url: '/subscription';
};

export type UnsubscribeErrors = {
    /**
     * Missing x-subscription-token header
     */
    400: ErrorResponse;
    /**
     * Subscription not found
     */
    404: ErrorResponse;
};

export type UnsubscribeError = UnsubscribeErrors[keyof UnsubscribeErrors];

export type UnsubscribeResponses = {
    /**
     * Subscription deactivated
     */
    200: SubscriptionResponse;
};

export type UnsubscribeResponse = UnsubscribeResponses[keyof UnsubscribeResponses];

export type GetSubscriptionData = {
    body?: never;
    headers: {
        /**
         * The subscription token received when creating a subscription
         */
        'x-subscription-token': string;
    };
    path?: never;
    query?: never;
    url: '/subscription';
};

export type GetSubscriptionErrors = {
    /**
     * Missing x-subscription-token header
     */
    400: ErrorResponse;
    /**
     * Subscription not found or expired
     */
    404: ErrorResponse;
};

export type GetSubscriptionError = GetSubscriptionErrors[keyof GetSubscriptionErrors];

export type GetSubscriptionResponses = {
    /**
     * Subscription status
     */
    200: SubscriptionResponse;
};

export type GetSubscriptionResponse = GetSubscriptionResponses[keyof GetSubscriptionResponses];

export type SubscribeData = {
    body?: never;
    headers: {
        /**
         * The subscription token received when creating a subscription
         */
        'x-subscription-token': string;
    };
    path?: never;
    query?: never;
    url: '/subscription';
};

export type SubscribeErrors = {
    /**
     * Missing x-subscription-token header
     */
    400: ErrorResponse;
    /**
     * Subscription not found
     */
    404: ErrorResponse;
};

export type SubscribeError = SubscribeErrors[keyof SubscribeErrors];

export type SubscribeResponses = {
    /**
     * Subscription activated
     */
    200: SubscriptionResponse;
};

export type SubscribeResponse = SubscribeResponses[keyof SubscribeResponses];

export type CreateSubscriptionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/subscription/create';
};

export type CreateSubscriptionResponses = {
    /**
     * New subscription created
     */
    201: SubscriptionResponse;
};

export type CreateSubscriptionResponse = CreateSubscriptionResponses[keyof CreateSubscriptionResponses];

export type GetPublicationConfigData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/publication/config';
};

export type GetPublicationConfigResponses = {
    /**
     * Publication configuration
     */
    200: {
        success?: boolean;
        data?: {
            publicationName?: string;
            language?: string;
            /**
             * Feature flags indicating which publication features are enabled.
             */
            features?: {
                newsletter?: boolean;
                bookmarks?: boolean;
                comments?: boolean;
                darkMode?: boolean;
                searchSuggestions?: boolean;
            };
            socialLinks?: {
                twitter?: string;
                github?: string;
                discord?: string;
            };
            seo?: {
                defaultTitle?: string;
                titleTemplate?: string;
                defaultDescription?: string;
            };
        };
    };
};

export type GetPublicationConfigResponse = GetPublicationConfigResponses[keyof GetPublicationConfigResponses];

export type HealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckResponses = {
    /**
     * Service health status
     */
    200: {
        success?: boolean;
        data?: {
            status?: string;
            timestamp?: string;
            services?: {
                redis?: 'connected' | 'error';
            };
        };
    };
};

export type HealthCheckResponse = HealthCheckResponses[keyof HealthCheckResponses];
